---
- name: Ensure these VLANs are not being tagged on the trunk
  hosts: nexus
  gather_facts: no


  vars:
    nxos_provider:
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      host: "{{ inventory_hostname }}"
      when: ansible_network_os == 'nxos'


  tasks:

      - name:  Ensure these VLANs are not being tagged on the trunk
        nxos_l2_interface:
         provider: "{{ nxos_provider }}"
         name: Ethernet1/5
         mode: trunk
         trunk_vlans: 3-20
         state: absent
  
                                                                                                                              configure ansible_network_os value for this host"}
